Vagrant.configure("2") do |config|
  config.vm.box = "eurolinux-vagrant/centos-stream-9"

   config.vm.network "private_network", ip: "192.168.56.27"
   config.vm.network "public_network"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

   config.vm.provision "shell", inline: <<-SHELL
     yum install httpd wget unzip vim -y
     systemctl start httpd
     systemctl enabled httpd
     mkdir -p /tmp/videogame
     cd /tmp/videogame
     wget https://github.com/Dvzr2k/Front-End-VideogameStore/archive/refs/heads/master.zip
     unzip -o master.zip
     cp -r Front-End-VideogameStore-master/* /var/www/html/
     systemctl restart httpd
     cd /tmp/
     rm -rf /tmp/videogame
   SHELL
end
